### ISSUE TITLE
Least Cost Path - error

### ISSUE THREAD

**Issue by driansmith** [Gooong/LeastCostPath#5]
The size of cost raster is: 18000 * 18000
Searching least cost path...
Traceback (most recent call last):
File "C:/Users/Bing/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\leastcostpath\least_cost_path_algorithm.py", line 236, in processAlgorithm
min_cost_path, costs, selected_end = dijkstra(start_row_col, end_row_cols, matrix, feedback)
File "C:/Users/Bing/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\leastcostpath\dijkstra_algorithm.py", line 125, in dijkstra
cost_so_far[nex] = new_cost
MemoryError

Execution failed after 814.09 seconds

Loading resulting layers
Algorithm 'Least Cost Path' finished
----------------------------------------------
Is this because the pc ran out of memory? the task was too big?

**Comment by Gooong** [comment]
Probably. `18000 * 18000` raster is rather large. You can have a try with more memory or simplify/resample the cost grid.
